name: Bump Version and Release

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Git identity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"          

      - name: Bump patch version
        run: npm version patch

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git push origin main --tags
          git push